backend:
  name: github
  repo: Peoples-University/website
  branch: main
  base_url: https://decap-proxy-production-88da.up.railway.app   # from the OAuth proxy step

media_folder: "assets/images"
public_folder: "/website/assets/images"

collections:

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Author", name: "author", widget: "string", default: "People's University Committee"}
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "journal-articles"
    label: "Journal Articles"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "People's University Committee"}
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "People's University"}
      - { label: "Live Demo URL", name: "demo_url", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "quartolayout" }

  - name: "studies"
    label: "Studies"
    folder: "_studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "People's University Committee"}
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
  
  - name: "orgschool"
    label: "Organizer School"
    folder: "_orgschool26"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Unit", name: "unit", widget: "number" }
      - { label: "Week", name: "week", widget: "number" }
      - { label: "Date", name: "datestring", widget: "string", hint: "eg: 23 December 1999" }
      - { label: "Time", name: "time", widget: "string", hint: "Eg: 1pm - 6pm" }
      - { label: "Slide URL", name: "slide_url", widget: "string", hint: "URL to the presentation slides" }
      - { label: "Author", name: "author", widget: "string", default: "People's University Committee"}
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Location", name: "location", widget: "string" }
      - name: "books"
        label: "Reading List"
        widget: "list"
        required: false
        fields:
          - { label: "Reading Title", name: "reading_title", widget: "string" }
          - { label: "Reading Author", name: "reading_author", widget: "string" }
          - { label: "Reading Page Count", name: "reading_pagecount", widget: "number" }
          - { label: "Reading Link", name: "reading_link", widget: "string" }
      - { label: "Summary", name: "summary", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "os_layout" }

  - name: "events"
    label: "Past Events"
    folder: "_events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string", hint: "Format as DD-MM-YYY" }
      - { label: "Time", name: "time", widget: "string", hint: "Eg: 1pm - 6pm" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Calendar Link", name: "calendarlink", widget: "string" }
      - { label: "Registration Link", name: "registerlink", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "People's University Committee"}
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
